### ISSUE TITLE
support updating d-rats

### ISSUE THREAD

**Issue by maurizioandreotti** [rafael2k/d-rats#3]
Hi ,
i am Maurizio iz2lxi, i am tring to update d-rats (some debug and few improvements) and seems you' tried doing some work on this in the past. if you are still interested in d-rats you could support - even slivhgtest contrib will be appreciated

my code review is here: https://github.com/maurizioandreotti/D-Rats

**Comment by rafael2k** [comment]
Thanks Maurizio. I'll point a link to your code in the README of my repo.
